### ISSUE TITLE
Got error': 401 Unauthorized

### ISSUE THREAD

**Issue by janm84** [codechimp-org/lms-tvh#20]
Hello everyone,

Maybe it's not an real issue, but i can't connect to my tvh server.

The Squeezeserverlog says:
[19-07-27 20:06:19.3721] Plugins::TVH::API::__ANON__ (124) Got error': 401 Unauthorized
[19-07-27 20:06:19.3733] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Networking::Async::_async_read: Not an ARRAY reference at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/TVH/Plugin.pm line 86.
; fh=Slim::Networking::Async::Socket::HTTP=GLOB(0x59746f8)

I followed the configuration example given in the readme file.
Nothins is missspelled and the tvh configuration for allowed networks is set to 0.0.0.0/0.

Maybe someone can help me please.

Best regards

Jan

**Comment by andrew-codechimp** [comment]
I've only tested this against TVHeadend version 4.2.1  If you are using something else that may be the issue.

Have you created a squeeze user on TVH and set that up under LMS plugin settings?
It should work without a user being specified but I use it with, if your using a different version TVH may have changed what's accessible on the API when not using a user account.

**Comment by janm84** [comment]
Today I've changes some settings regarding authentication (general tab - > authentication type = both digest and plain) now it's working.Is the plugin filtering the services against any tags? Not every services is shown in the plugin. Am 28.07.2019 17:57 schrieb Andrew Jackson <notifications@github.com>:I've only tested this against TVHeadend version 4.2.1  If you are using something else that may be the issue.
Have you created a squeeze user on TVH and set that up under LMS plugin settings?
It should work without a user being specified but I use it with, if your using a different version TVH may have changed what's accessible on the API when not using a user account.

**Comment by andrew-codechimp** [comment]
Glad you got it working, I've never touched the authentication type so that's a new one I'll add to the readme.

It doesn't filter at all, every tag/every channel should be displayed.  Is there anything unusual about the ones that are not?

**Comment by janm84** [comment]
Maybe some services/channels don't have tags. I will check later and give you a feedback. Am 28.07.2019 18:41 schrieb Andrew Jackson <notifications@github.com>:Glad you got it working, I've never touched the authentication type so that's a new one I'll add to the readme.
It doesn't filter at all, every tag/every channel should be displayed.  Is there anything unusual about the ones that are not?

**Comment by thiemo** [comment]
I had the same issues getting the `Plugins::TVH::API::__ANON__ (124) Got error': 401 Unauthorized` error message. Switching to _Authentication type: both plain and digest_ in TVHeadend solved the issue.
